// reblue - ReXGlue Recompiled Project
// Generated by: rexglue migrate
//
// This file is SDK-managed. Customizations go in virtual hook overrides.
// Running 'rexglue migrate' will overwrite this file.

#include "generated/reblue_config.h"
#include "generated/reblue_init.h"
#include "bdengine/heap.h"
#include "bdengine/bd_init.h"

#include <rex/rex_app.h>

#include "bdengine/bd_init.h"

class ReblueApp : public rex::ReXApp {
 public:
  using rex::ReXApp::ReXApp;

  static std::unique_ptr<rex::ui::WindowedApp> Create(
      rex::ui::WindowedAppContext& ctx) {
    return std::unique_ptr<ReblueApp>(new ReblueApp(ctx, "reblue",
        {PPC_CODE_BASE, PPC_CODE_SIZE, PPC_IMAGE_BASE,
         PPC_IMAGE_SIZE, PPCFuncMappings}));
  }

 protected:
  void OnPostSetup() override {
      // Initialize native heap (replaces game's NT heap allocator with dlmalloc)
      bd::InitNativeHeap();
    // Initialize native file I/O hooks (CreateFileA, ReadFile, etc.)
    bd::InitFileHooks(runtime()->game_data_root());

    // Initialize game patches
    bd::InitGamePatches();
  }
};

REX_DEFINE_APP(reblue, ReblueApp::Create)
